from sklearn.metrics import f1_score, precision_score, average_precision_score
import numpy as np
data = np.random.rand(1000, 3)
label = np.random.rand(1000, 3)
data = np.divide(np.exp(data), np.sum(np.exp(data), axis=-1, keepdims=True))
data = np.argmax(data, -1)
label = np.where(label == np.max(label, axis=-1, keepdims=True), 1., 0.)
label = np.argmax(label, axis=-1)
print(f1_score(data, label, average='macro'))
# print(f1_score(y_true, y_pred, average='micro'))
# print(f1_score(y_true, y_pred, average='weighted'))
# print(f1_score(y_true, y_pred, average=None))
# print(precision_score(data, label, average='macro', zero_division=0))
# print(precision_score(y_true, y_pred, average='micro', zero_division=0))
# print(precision_score(y_true, y_pred, average='weighted', zero_division=0))
# print(precision_score(y_true, y_pred, average=None, zero_division=0))
# print(average_precision_score(data, label, average='macro'))
# print(average_precision_score(y_true, y_pred, average='micro'))
# print(average_precision_score(y_true, y_pred, average='weighted'))
# print(average_precision_score(y_true, y_pred, average=None))
